name: Auto Decompile APK

on:
  push:
    paths:
      - '*.apk'
  workflow_dispatch:

jobs:
  decompile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.MY_TOKEN }}

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install JADX
        run: |
          wget https://github.com/skylot/jadx/releases/download/v1.5.0/jadx-1.5.0.zip
          unzip jadx-1.5.0.zip -d jadx_bin
          echo "$(pwd)/jadx_bin/bin" >> $GITHUB_PATH

      - name: Decompile APK
        run: |
          APK_FILE=$(ls *.apk | head -n 1)
          if [ -f "$APK_FILE" ]; then
            ./jadx_bin/bin/jadx -d out_source "$APK_FILE"
          else
            echo "No APK found!" && exit 1
          fi
          # تنظيف الملفات الكبيرة فوراً قبل مرحلة الـ Git
          rm -rf jadx-1.5.0.zip jadx_bin

      - name: Commit and Push
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
        run: |
          git config --global user.name "Jasserbelloumi"
          git config --global user.email "jasser@github.com"
          # إضافة المجلدات البرمجية فقط وتجنب أي ملفات مضغوطة
          git add out_source/ README.md
          git commit -m "Success: Clean decompile without large files" || echo "No changes"
          git push origin HEAD
